### ISSUE TITLE
Home Assistant integration planned?

### ISSUE THREAD

**Issue by adetante** [djtimca/hagooglewifi#12]
This integration looks very interesting! Thanks for the work.

Is it planned to integrate it into home assistant core?
Can I try to do a PR for this integration?

**Comment by djtimca** [comment]
I may look to move it to core at some point. Right now just trying to get the kinks worked out. There seem to be some challenges with some systems / setups which would need a fair bit more work to get this to a state to be ready to bring into core, but at some point I will look at it. 

I have a couple others in various states of inclusion in core - it is a long process. 

For now will just stick to HACS inclusion to continue to flush out issues and features.

**Comment by adetante** [comment]
Ok, got it. Thanks for the feeeback!
