### ISSUE TITLE
Configuration enhancement

### ISSUE THREAD

**Issue by alexanderpett** [djtimca/hagooglewifi#13]
Hi, thank you for this beautiful integration of google wifi! You're awesome!
In reference to the enhancement you made in #4, I would like to suggest there be added a configuration to select which home to be included, and/or make the home show as an attribute at the different entities (to use as device trackers for multiple homes?).

Cheers, and happy holidays! 👍

**Comment by djtimca** [comment]
OK I have added the system ID as an attribute to all entities in the next release. Home selection will be more involved, and can be solved by setting up the integration with entities default disabled, and then just enabling the specific entities from the specific home(s) you want to include.
