### ISSUE TITLE
Google wifi regularly crashes 

### ISSUE THREAD

**Issue by littlbee** [djtimca/hagooglewifi#16]
It seems that since I installed this module my Google wifi router regularly crashes. I suspect the module might be polling for data too frequently.
I'll disable the module and report back in a couple of days, see if the crashes have stopped.

**Comment by djtimca** [comment]
This has been reported for some people but it is inconsistent. There is an option on the integration to change your polling interval as well so you can adapt the polling interval to fit your system.

**Comment by littlbee** [comment]
Just FYI, the crashes stopped once I removed the speed tests from the settings
