### ISSUE TITLE
Won't Populate Entities after being installed

### ISSUE THREAD

**Issue by DrSeussFreak** [djtimca/hagooglewifi#23]
Fresh install of this add-on, restarted the core and I am consitently receiving this error

> 2021-01-21 11:14:29 WARNING (MainThread) [homeassistant.config_entries] Config entry for googlewifi not ready yet. Retrying in 40 seconds
> 2021-01-21 11:15:03 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
> 2021-01-21 11:15:33 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
> 2021-01-21 11:15:34 WARNING (MainThread) [homeassistant.config_entries] Config entry for googlewifi not ready yet. Retrying in 80 seconds

uninstalled it, restarted, re-installed it, using a new key, same issue.

**Comment by djtimca** [comment]
The two errors in the middle don't appear to be related to this integration - they are coming from the google_assistant component which is not used by the googlewifi integration.

I can see that you are getting not ready yet errors which _should_ include a separate debut message of "Google WiFi API: {error}" when it gets thrown.

You may need to add debug logging for the googlewifi integration to your configuration.yaml to see them.
```
logger:
  default: warning
  logs:
    homeassistant.components.googlewifi: debug
```

**Comment by DrSeussFreak** [comment]
I've added that to my config file and restarted.  Still only receiving this in the core section of supervisor logs

> 2021-01-21 12:33:42 ERROR (MainThread) [custom_components.googlewifi] Error fetching GoogleWifi data: Error connecting to GoogleWifi: 
> 2021-01-21 12:33:42 WARNING (MainThread) [homeassistant.config_entries] Config entry for googlewifi not ready yet. Retrying in 80 seconds

am I looking in the right spot?

**Comment by djtimca** [comment]
It would appear that for some reason your Home Assistant is getting a timeout when it is calling the Google Wifi cloud APIs. Are you able to hit this URL directly from the Home Assistant box (or at least from your network)? Not sure if there might be some sort of network issue blocking you? 

https://googlehomefoyer-pa.googleapis.com/v2/groups?prettyPrint=false

You should a response like:
```
{
  "error": {
    "code": 401,
    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}
```

**Comment by DrSeussFreak** [comment]
Just ran wget from command line

```
config $ wget googlehomefoyer-pa.googleapis.com/v2/groups?prettyPrint=false
--2021-01-21 12:52:02--  http://googlehomefoyer-pa.googleapis.com/v2/groups?prettyPrint=false
Resolving googlehomefoyer-pa.googleapis.com (googlehomefoyer-pa.googleapis.com)... 172.217.1.42, 2607:f8b0:4001:c07::5f
Connecting to googlehomefoyer-pa.googleapis.com (googlehomefoyer-pa.googleapis.com)|172.217.1.42|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-01-21 12:52:02 ERROR 403: Forbidden.
```

**Comment by djtimca** [comment]
Interesting... I get the same from my server where HA is hosted. It looks like you are getting the connection through, but for some reason still getting a timeout on the actual requests.

Unfortunately it doesn't look like there is an error being returned, it is just getting a timeout. 

Unfortunately not a lot more I can validate from this. Only thing I could suggest is (if you're comfortable) doing some manual testing using the googlewifi python library at https://github.com/djtimca/googlewifi-api to see if you can get additional logging from your own system. It will likely require you to do a little digging in code, but I can't reproduce this error on my own network, dev machine, or production HA environment.

**Comment by DrSeussFreak** [comment]
ok, I will take a look.  Thanks for the quick responses.

**Comment by DrSeussFreak** [comment]
Quick question, does the name I provide when getting the token matter?

**Comment by djtimca** [comment]
I don't think so. Are you using the Chrome plugin? That has been the most successful method.

**Comment by DrSeussFreak** [comment]
I am using the plugin, yes.  I removed the integration and add-on, rebooted the entire box.  ran wget, got 401 NOT 403.  Reinstalled the plugin, rebooted.  Added the integration, and I am seeing the same errors, EXCEPT wget still returns 401, not 403 like earlier.

**Comment by djtimca** [comment]
401 sounds more promising. I can't seem to call from within my HA docker to see what I get there. I get 403 from the server terminal so still not sure if that means anything.

**Comment by DrSeussFreak** [comment]
Not sure what to do next though, hehe

**Comment by djtimca** [comment]
Unfortunately me either! Sorry, just not enough in the errors to isolate why yours won't connect.

**Comment by DrSeussFreak** [comment]
no worries, I'll play around some more

**Comment by djtimca** [comment]
I actually had this happen to my own config yesterday. I had to remove the integration, get a new token, and reinstall. 

After reinstalling I had no devices/entities so I just left it - eventually it was able to pick everything up and pull it in, but it might have taken an extra Home Assistant reboot than I was expecting.

Appears to be related to the ability to connect to the Google servers (which I was having trouble with). It did eventually work, just required patience and waiting.
