### ISSUE TITLE
Device trackers show state "unavailable" for 1 minute randomly before reverting to correct state

### ISSUE THREAD

**Issue by nathbullen** [djtimca/hagooglewifi#25]
As the title says, trackers show "unavailable" for little 1 min intervals randomly throughout the day before reverting to Home/Away

**Comment by djtimca** [comment]
This will happen if your system can't connect to Google for updates. Try reducing the update frequency if possible (I'm set to 120 seconds on mine and it does happen still periodically, but less often).

**Comment by droopanu** [comment]
Would it be possible to leave the status unchanged in case of connection error instead of making it unavailable?
