### ISSUE TITLE
Device tracker never reports devices home

### ISSUE THREAD

**Issue by siminn-gretarp** [djtimca/hagooglewifi#27]
All the device trackers of my Goole wifi detected devices report away or unavailable and never home status. I installed and configured the integration as the documentation describes. Is there something more to it like configure some device tracker settings?

**Comment by djtimca** [comment]
Does the rest of the integration work correctly (ie. you can pause/unpause devices etc)?

**Comment by kptrsen** [comment]
I have a similar problem where the switch entities works but not the device trackers.   Looks to be related to not getting unique entity ids, getting this in the log
Platform googlewifi does not generate unique IDs.

**Comment by daviegeepers** [comment]
I am also having this issue. All my devices are "Away", the on/off switch is marked On as default. I can turn it off and the device stops responding. I can click the switch again and the device resumes normal function.

**Comment by djtimca** [comment]
I have just started to see this behaviour as well so will try to troubleshoot over the next few weeks.

**Comment by djtimca** [comment]
I think this should be fixed now. Make sure that IOS devices do not have Private Address set in the Wifi settings or they will keep disappearing (and being recreated as a new device) when their MAC address changes.
