### ISSUE TITLE
[custom_components.googlewifi] Unexpected error fetching GoogleWifi data: 'operationState'

### ISSUE THREAD

**Issue by droopanu** [djtimca/hagooglewifi#30]
Every now and then all devices go unavailable for a little while, and I can see the following error in logs:

> 2021-04-15 15:06:43 ERROR (MainThread) [custom_components.googlewifi] Unexpected error fetching GoogleWifi data: 'operationState'
> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
>     self.data = await self._async_update_data()
>   File "/home/homeassistant/.homeassistant/custom_components/googlewifi/__init__.py", line 171, in _async_update_data
>     system_data = await self.api.get_systems()
>   File "/srv/homeassistant/lib/python3.8/site-packages/googlewifi/__init__.py", line 191, in get_systems
>     return await self.structure_systems(response)
>   File "/srv/homeassistant/lib/python3.8/site-packages/googlewifi/__init__.py", line 284, in structure_systems
>     sensitive_info = await self.get_sensitive_info(system_id=this_system["id"], station_ids=station_ids)
>   File "/srv/homeassistant/lib/python3.8/site-packages/googlewifi/__init__.py", line 616, in get_sensitive_info
>     status = status["operationState"]
> KeyError: 'operationState'

**Comment by djtimca** [comment]
This happens periodically if the Google APIs return invalid data. Because of the nature of this integration using the back door to those cloud APIs it will not be perfect on those.
