### ISSUE TITLE
Error: Abort Single Instance Allowed - maybe caused by multiple GWifi locations

### ISSUE THREAD

**Issue by ahochsteger** [djtimca/hagooglewifi#32]
When adding the Google Wifi integration I get the following error message:
```[%key:common::config_flow::abort::single_instance_allowed%]```

hagooglewifi version: 0.1.25
Home Assistant: 2021.4.5

It may be caused by the fact, that I manage two Google Wifi installations on different locations but it I'm sure it has been working some weeks ago when I last tried out this integration.

**Comment by djtimca** [comment]
Yes - you can only install the integration once. If it is already active in your HA instance you can't add it again.

**Comment by ahochsteger** [comment]
@djtimca thanks for your response - I thought it had to do with multiple households as mentioned in #21 but in fact I already had the integration added but disabled so I didn't see it.
