### ISSUE TITLE
Owner of multiple wifi points

### ISSUE THREAD

**Issue by judeibe** [djtimca/hagooglewifi#4]
I manage my parent's wifi points as well as mine. Is it possible as part of the integration to choose which group to use? I messed around with the API and looks as if an array of groups is passed if the user has more than one.

**Comment by djtimca** [comment]
I don't have a way to test that scenario to see what data is returned. Are you able to post a sample file which would highlight how that data is represented when it is returned from the API?

**Comment by judeibe** [comment]
On this api call `https://googlehomefoyer-pa.googleapis.com/v2/groups?prettyPrint=false` the googlewifi library seems to pull the first id from groups. This is from the postman collection

// The first system's ID
`pm.environment.set("system_id", jdata["groups"][0]["id"]);`

```javascript
{
    "groups": [
        {
            "id": "AAAAAA6aoPQ",
            ....,
        },
       {
           "id": "AAAAABhsip0",
           ....,
        }
     ]
}

```

**Comment by djtimca** [comment]
That is odd then... in my library I iterate through the groups to capture all systems that are returned. Is the pm.environment code you listed from postman somewhere that I can look at?

**Comment by judeibe** [comment]
This is the link to the collection https://documenter.getpostman.com/view/7490211/SzzdD1pF?version=latest

**Comment by djtimca** [comment]
Thanks @judeibe that's one of the docs I've been using to pull this together. But I am actually iterating through the systems in groups in my library so I'm wondering if the issue might be that Google isn't actually returning all of the systems under the account. Might be related to the token approach to authentication. I'll see if I can't put together a tool to get some test data in the way I'm pulling it so i can validate.

**Comment by judeibe** [comment]
I'll take a look at the api and if I can pin point the issue I'll create an issue or pr.

**Comment by djtimca** [comment]
Fixed in latest push. Thanks @judeibe!
