### ISSUE TITLE
Consistent KeyError: 'traffic' error

### ISSUE THREAD

**Issue by DerekF35** [djtimca/hagooglewifi#40]
I've tried to track down this one myself as well a looked to see if it was asked and answered but couldn't find, so I apologize if it was.

I'm repeatedly getting the following error.  It will process fully sometimes,  but not often than not I get this exception and all devices lose their states and attributes.

UPDATE: After more digging #39  reported same key error, but with others asking with it. I always get the traffic key error.

```2021-07-02 22:14:27 ERROR (MainThread) [custom_components.googlewifi] Unexpected error fetching GoogleWifi data: 'traffic'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/googlewifi/__init__.py", line 171, in _async_update_data
    system_data = await self.api.get_systems()
  File "/usr/local/lib/python3.8/site-packages/googlewifi/__init__.py", line 191, in get_systems
    return await self.structure_systems(response)
  File "/usr/local/lib/python3.8/site-packages/googlewifi/__init__.py", line 291, in structure_systems
    devices[this_station["station"]["id"]]["traffic"] = this_station["traffic"]
KeyError: 'traffic'

**Comment by jsnfwlr** [comment]
I've also got this exact issue with my 3-puck Gen1 Google WiFi setup.

Initially it started with the upload/download speed values showing as 'unknown', then I restarted Home Assistant and the whole integration failed to load with the error @DerekF35 has reported.

I have completely removed and reinstalled the integration in an attempt to fix it, but nothing has changed.

**Comment by DerekF35** [comment]
Was also (probably more properly) reported on the googlewifi-api package. 

https://github.com/djtimca/googlewifi-api/issues/3

**Comment by djtimca** [comment]
Fixed in 0.1.26 release

**Comment by gmlupatelli** [comment]
Just updated the integration and will let it run to check for errors! Thanks for the update. :)

**Comment by djtimca** [comment]
Make sure you grab latest - I pushed three versions today with various fixes.
