### ISSUE TITLE
Google Refresh Token

### ISSUE THREAD

**Issue by absolutelyNothing9** [djtimca/hagooglewifi#48]
To install this integration you will need a Google Refresh Token which you can get by following the instructions at: https://www.angelod.com/onhubauthtool

There are no instructions there on what in the hell I'm supposed to be doing. Perhaps you should consider explaining what in the hell a person is supposed to be doing with this stupid little junky webpage.

**Comment by djtimca** [comment]
Doesn't seem like the best approach to get help.

**Comment by absolutelyNothing9** [comment]
> Doesn't seem like the best approach to get help.

So your choice, instead of offering clear, concise directions, is to close the issue rather than correct it. You are a fucking idiot. You should shoot yourself in the fucking face you piece of shit
