### ISSUE TITLE
Cannot add integration through HACS

### ISSUE THREAD

**Issue by pjcarly** [djtimca/hagooglewifi#52]
Cannot add integration through HACS, I'm using the (as of writing) latest version of HACS (version 1.15.2)

When clicking "Explore & Add Repositories" and searching for "Google Wifi", I get no response:
![image](https://user-images.githubusercontent.com/2808694/139600598-a350d791-216b-46b1-9462-fb85e86d47c3.png)

When trying to add the repository via "Custom Repositories", I cannot add it:
![image](https://user-images.githubusercontent.com/2808694/139600572-cdd915ba-0044-4351-9114-b5f586c5d315.png)

**Comment by djtimca** [comment]
Unfortunately this appears to be an issue with your install of HACS.
