### ISSUE TITLE
Tool for finding oauth token seems broken

### ISSUE THREAD

**Issue by aaronsarna** [djtimca/hagooglewifi#55]
I tried following the instructions at https://www.angelod.com/onhubauthtool/ and also using the chrome extension, but, after logging in, both just end of taking me to https://accounts.google.com/embedded/close without showing me anything resembling an oauth token. Maybe something changed on the Google side?

**Comment by ViPeR5000** [comment]
+1

**Comment by aaronsarna** [comment]
That was the chrome extension that I mentioned I had already tried, and it has the same problem as the manual method.

**Comment by djtimca** [comment]
I just tested the Chrome extension again and it is working as expected and returning a token.

**Comment by aaronsarna** [comment]
So what am I to make of the fact that it silently fails for me? Are there any debugging steps I can take? I am a software engineer, and have some familiarity with Chrome extensions and general web technologies, so I'm happy to do a deep dive, but I don't know where to start on this.

**Comment by djtimca** [comment]
Unfortunately I did not author that tool so I'm not sure of any steps to debug what's happening for you. I'm only aware of the two methods documented to get the required token. There has been a suggestion to add login to this integration which would generate the token automatically, but unfortunately I won't likely have time to look at it to enhance it for the forseeable future.

If anyone else wants to work to improve that part I'm happy to review and entertain pull requests, I just don't have time between my regular jobs to look at it right now and it's low on my HA list of priorities at the moment.

**Comment by aaronsarna** [comment]
Ok thanks. I opened https://github.com/AngeloD2022/onhubauthhelper/issues/1, so hopefully the extension author will have some ideas.

**Comment by ViPeR5000** [comment]
> I just tested the Chrome extension again and it is working as expected and returning a token.

work for me too today

**Comment by aaronsarna** [comment]
Seems to have been related to being logged into multiple Google accounts at once.
