### ISSUE TITLE
Error setting up googlewifi integration on 2022.4.0b0

### ISSUE THREAD

**Issue by thewazz1** [djtimca/hagooglewifi#66]
Running HA beta 2022.4.0b0 and getting the following error message, and googlewifi will not load

2022-03-31 15:14:16 ERROR (SyncWorker_2) [homeassistant.util.package] Unable to install package grpcio==1.44.0: ERROR: Cannot install grpcio==1.44.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
2022-03-31 15:14:16 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration googlewifi: Requirements for googlewifi not found: ['grpcio==1.44.0'].

**Comment by djtimca** [comment]
Unfortunately this will need the updated version of grpcio to be released before I can resolve. There is a release candidate out for it, but not released yet. Not sure if the new version will resolve either. Will keep my eye on it.

**Comment by Mezzle** [comment]
What is this conflicting with? It seems the error message isn't stating

**Comment by CZonin** [comment]
No additional info to add, but also experiencing this with 2022.4.0

**Comment by j-loewen** [comment]
> Also experiencing on 2022.4.0

Yes, same here

**Comment by Mezzle** [comment]
It seems you're depending on a version of `googlewifi` that's been yanked from github?  Whilst it appears in pypi, if you look at the [Github Tags](https://github.com/djtimca/googlewifi-api/tags) - there's no version there that's linked.

https://github.com/djtimca/googlewifi-api/tags

I'm not 100% sure where the pypi version 0.0.20 has come from, as it doesn't offer a tag, or a diff on pypi, and it seems the new version of grpc has been yanked from release?

It might be worth downgrading it back to 0.0.19 temporarily? Although this will regress #61

**Comment by thewazz1** [comment]
I did some poking around, and it looks like Home Assistant uses grpcio 1.45.0, even though it was yanked from PyPi.  So just to try it out I changed grpcio to 1.45.0 in the manifest.json, and restarted HA.  Googlewifi came up and it appears to be working.  Since it is included in HA itself, the explicit dependency may even be able to be removed from this custom component.

**Comment by djtimca** [comment]
Thanks @thewazz1 - was on my list to look at today. Appreciate the troubleshoot! Will get a new release out today.

**Comment by Mezzle** [comment]
> I changed grpcio to 1.45.0 in the manifest.json, and restarted HA. Googlewifi came up and it appears to be working. 

This worked for me also. Really appreciate that fix @thewazz1 .  Just wish I knew Python etc better to be able to have found this myself!

**Comment by kreene1987** [comment]
Worked for me as well!

**Comment by bfish2** [comment]
Thanks everyone!  Worked for me too!

**Comment by CZonin** [comment]
All good for me now too after the update. Thanks!
