### ISSUE TITLE
Integration not ready yet error

### ISSUE THREAD

**Issue by digitalwolf** [djtimca/hagooglewifi#68]
I'd been running this integration until the issue with the 0.1.30 release, so I removed it.  I'm trying to install and use the 0.1.31 release.  It installs successfully, and I can set up the integration with my key, but it never actually starts.  I've restarted HA multiple times, and I just cannot get it to start.  I keep getting this in the logs:

`2022-04-10 11:48:17 ERROR (MainThread) [custom_components.googlewifi] Error fetching GoogleWifi data: Error connecting to GoogleWifi:
2022-04-10 11:48:17 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Google Wifi' for googlewifi integration not ready yet: None; Retrying in background
`

Has anyone had success with this version?

**Comment by DerekF35** [comment]
I hit this issue.  Router restart seed to have solved it.  I noticed in my Home app the router was showing as offline even though it was working fine.  I also deleted and resetup the integration a bunch of times, but nothing worked until the hard restart of router.

**Comment by digitalwolf** [comment]
Sure enough, that was my problem.  Thanks for the help.
