### ISSUE TITLE
Config flow could not be loaded: undefined

### ISSUE THREAD

**Issue by stonkage** [djtimca/hagooglewifi#70]
Hi there

When i try to install the integration i get the following error "Config flow could not be loaded: undefined"

I can see the following in the log

Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 12:15:20 (3 occurrences)
Last logged: 12:16:07

Unable to install package grpcio==1.44.0: ERROR: Cannot install grpcio==1.44.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

## System Health

version | core-2022.4.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.15.32-v8
arch | aarch64
timezone | Australia/Adelaide

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.24.5
Stage | running
Available Repositories | 1027
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 17 May 2022, 09:30
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | ap-southeast-1-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.0.rc2
-- | --
update_channel | beta
supervisor_version | supervisor-2022.04.2
docker_version | 20.10.12
disk_total | 58.0 GB
disk_used | 7.7 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.3.0), Node-RED (11.1.1), Studio Code Server (5.0.0), Home Assistant Google Drive Backup (0.106.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 1
views | 15
mode | storage

</details>

any help would be much appreciated

**Comment by rmiles7721** [comment]
Getting the same thing here.

022-04-23 20:16:13 INFO (MainThread) [homeassistant.requirements] Multiple attempts to install grpcio==1.44.0 failed, install will be retried after next configuration check or restart

**Comment by djtimca** [comment]
I just created a new release which should fix this. Sorry must have missed creating the release with the last update.

**Comment by paulgampe** [comment]
Trying the new version did not resolve this issue for me.
