### ISSUE TITLE
current in/out usage?

### ISSUE THREAD

**Issue by douglasmauro** [djtimca/hagooglewifi#9]
(Q1) Is there a way with to see total (internet) in/out bps?

(Q2) show specific device ie kids computer in/out bps?

(Q3) If there's a switch connected to a google mesh router, how will those devices on the switch show up?

**Comment by djtimca** [comment]
Q1 - the overall WLAN speed test is now available as sensors, however I have not yet found any calls which would enable me to report real time traffic

Q2 - similarly at the device level I have not yet tracked how to do device level speed tests or real time traffic levels

Q3 - Anything on the switch will show up as devices on the network. I have a similar setup in my network and all devices beyond the switch just show up as connected devices in the same way.

I will add feature requests for Q1 and Q2 so I don't lose track of them as I continue to explore the API calls.
