### ISSUE TITLE
Seems incompatible with HA 2024.11.0b3

### ISSUE THREAD

**Issue by FrancoLoco** [djtimca/hagooglewifi#97]
Logger: homeassistant.util.package
Source: util/package.py:152
First occurred: 13:06:51 (6 occurrences)
Last logged: 13:07:49

Unable to install package googlewifi==0.0.21: × No solution found when resolving dependencies: ╰─▶ Because ghome-foyer-api==1.0.0 depends on protobuf>=4.21.12,<5.0.0 and protobuf==5.28.3, we can conclude that ghome-foyer-api==1.0.0 cannot be used. And because only ghome-foyer-api==1.0.0 is available, we can conclude that all versions of ghome-foyer-api cannot be used. And because googlewifi==0.0.21 depends on ghome-foyer-api and you require googlewifi==0.0.21, we can conclude that your requirements are unsatisfiable.
Unable to install package glocaltokens==0.7.1: × No solution found when resolving dependencies: ╰─▶ Because ghome-foyer-api==1.0.0 depends on protobuf>=4.21.12,<5.0.0 and protobuf==5.28.3, we can conclude that ghome-foyer-api==1.0.0 cannot be used. And because only ghome-foyer-api==1.0.0 is available, we can conclude that all versions of ghome-foyer-api cannot be used. And because glocaltokens==0.7.1 depends on ghome-foyer-api and you require glocaltokens==0.7.1, we can conclude that your requirements are unsatisfiable.

**Comment by djtimca** [comment]
Looks like this may be the end of the line for this integration until somebody has time to rewrite it using oath. New users have not been able to install it for some time, so I guess this will be the end for everyone.

**Comment by FrancoLoco** [comment]
Nice this was resolved:
https://github.com/KapJI/ghome-foyer-api/pull/124

and I can confirm it works now.
